### ISSUE TITLE
有没有一种方案可以让用户无感更新，项目是单项目多模块的那种单体应用

### ISSUE THREAD

**Issue by ideaviewes** [kytrun/snippets#1]
项目是单项目多模块的那种单体应用，没有用springcloud
我的思路是上传新的jar包后，把新的jar包启动起来，nginx发负载均衡配置两个端口，用最小相应时间那种策略
新的启动起来后，把老的关掉，这样就自动切到了新的端口上
但是这样每次更新代码都要改端口，感觉特别麻烦
针对这种场景，有什么简单有效的方案吗？

**Comment by kytrun** [comment]
> 项目是单项目多模块的那种单体应用，没有用springcloud
> 我的思路是上传新的jar包后，把新的jar包启动起来，nginx发负载均衡配置两个端口，用最小相应时间那种策略
> 新的启动起来后，把老的关掉，这样就自动切到了新的端口上
> 但是这样每次更新代码都要改端口，感觉特别麻烦
> 针对这种场景，有什么简单有效的方案吗？
> 

可以用 sh 脚本在 Java 启动命令中设定端口，参考随机端口那个脚本，可以设定范围，但是只要两个临近值，比如 8080-8081

**Comment by ideaviewes** [comment]
好的，多谢
